# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:

  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: echo "$SERVICE_ACCOUNT_CREDENTIALS" > serviceAccount.json
    - run: npm ci
    - run: npm run test:full

    env:
      FIREBASE_API_KEY: ${{secrets.DEVELOPMENT_FIREBASE_API_KEY}}
      FIREBASE_AUTH_DOMAIN: ${{secrets.DEVELOPMENT_FIREBASE_AUTH_DOMAIN}}
      FIRESTORE_URL: ${{secrets.DEVELOPMENT_FIRESTORE_URL}}
      FIREBASE_PROJECT_ID: ${{secrets.DEVELOPMENT_FIREBASE_PROJECT_ID}}
      FIREBASE_BUCKET: ${{secrets.DEVELOPMENT_FIREBASE_BUCKET}}
      FIREBASE_MESSAGING_ID: ${{secrets.DEVELOPMENT_FIREBASE_MESSAGING_ID}}
      FIREBASE_APP_ID: ${{secrets.DEVELOPMENT_FIREBASE_APP_ID}}
      SERVICE_ACCOUNT_CREDENTIALS: ${{secrets.SERVICE_ACCOUNT_CREDENTIALS}}

  deploy: 

    needs: test_and_build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: echo "$SERVICE_ACCOUNT_CREDENTIALS" > serviceAccount.json
    - run: npm ci
    - run: npm run deploy

    env:
      FIREBASE_API_KEY: ${{secrets.PRODUCTION_FIREBASE_API_KEY}}
      FIREBASE_AUTH_DOMAIN: ${{secrets.PRODUCTION_FIREBASE_AUTH_DOMAIN}}
      FIRESTORE_URL: ${{secrets.PRODUCTION_FIRESTORE_URL}}
      FIREBASE_PROJECT_ID: ${{secrets.PRODUCTION_FIREBASE_PROJECT_ID}}
      FIREBASE_BUCKET: ${{secrets.PRODUCTION_FIREBASE_BUCKET}}
      FIREBASE_MESSAGING_ID: ${{secrets.PRODUCTION_FIREBASE_MESSAGING_ID}}
      FIREBASE_APP_ID: ${{secrets.PRODUCTION_FIREBASE_APP_ID}}
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}